version: '3.8'

services:
  todo-db:
    image: postgres:16.1-alpine
    restart: always
    container_name: todo_db
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - ./data/db/volum:/var/lib/postgresql/data
    networks:
      - todo_nw

networks:
  todo_nw:
    external: true
